const questions=[
"Are you my super loved girlfriend?","Are you my sugar baby?","Will you ask me for everything you want from now on?","Are you perfect?","Are you wonderful?","Are you super sexy and hot?","Are you the love of my life?","Will I give you a white Jimny someday?","Are you fat?","Do I have a free wish?", "Do you promise me that no matter what happens, you will always count on me?" ];
const lines=["I love you infinitely, Celina ❤️","You are perfect","My princess","My future wife","I miss calling you señorita Celina, ngl", "i know you love my furby"];
let step=0, tries=0, heartClicks=0, audioOn=false, holdTimer, ctx;
const app=document.querySelector('#app'), particles=document.querySelector('#particles'), toast=document.querySelector('#toast');
function floating(n=28){particles.innerHTML='';for(let i=0;i<n;i++){let e=document.createElement('span');e.className='floating';e.textContent=Math.random()>.25?'♥':'✦';e.style.left=Math.random()*100+'vw';e.style.bottom=(-10-Math.random()*75)+'px';e.style.fontSize=(12+Math.random()*25)+'px';e.style.animationDuration=(7+Math.random()*9)+'s';e.style.animationDelay=(-Math.random()*12)+'s';particles.append(e)}}
floating();
function tone(){if(!audioOn)return;ctx??=new AudioContext();let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=660;g.gain.setValueAtTime(.045,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.13);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.13)}
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function burst(x=innerWidth/2,y=innerHeight/2,count=22){for(let i=0;i<count;i++){let e=document.createElement('i');e.className='heart-burst';e.textContent='♥';e.style.left=x+'px';e.style.top=y+'px';e.style.color=['#fff','#ff2d68','#ffc1d8'][i%3];e.style.fontSize=(14+Math.random()*22)+'px';e.style.setProperty('--x',(Math.random()-.5)*430+'px');e.style.setProperty('--y',(Math.random()-.5)*390+'px');document.body.append(e);setTimeout(()=>e.remove(),1600)}}
function renderQuiz(){app.className='screen quiz';app.innerHTML=`<section class="quiz-card glass"><p class="progress-label">QUESTION ${step+1} OF ${questions.length}</p><div class="bar"><i style="width:${(step+1)*10}%"></i></div><p class="love-line">${lines[step%lines.length]}</p><h2 class="question">${questions[step]}</h2><div class="answers"><button class="answer yes">YES</button><button class="answer no">NO</button></div></section>`;let yes=app.querySelector('.yes'),no=app.querySelector('.no'),fat=step===8;let correct=fat?no:yes, runner=fat?yes:no;correct.onclick=e=>{tone();burst(e.clientX,e.clientY);setTimeout(next,380)};runner.addEventListener('pointerenter',()=>escape(runner));runner.addEventListener('pointerdown',e=>{e.preventDefault();tries++;if(navigator.vibrate)navigator.vibrate(35);if(tries>4)showToast('Nice try 😌❤️');escape(runner)});if(!fat) no.onclick=e=>{e.preventDefault();escape(no)};tries=0}
function escape(btn){let r=btn.getBoundingClientRect(), pad=18, x=Math.max(pad,Math.min(innerWidth-r.width-pad,r.left+(Math.random()-.5)*260)),y=Math.max(80,Math.min(innerHeight-r.height-pad,r.top+(Math.random()-.5)*210));btn.classList.add('escaping');btn.style.left=x+'px';btn.style.top=y+'px';btn.style.transform=`rotate(${(Math.random()-.5)*18}deg) scale(${.92+Math.random()*.16})`}
function next(){step++;step<questions.length?renderQuiz():renderFinal()}
function renderFinal(){app.className='screen final';particles.innerHTML='';app.innerHTML=`<section class="final-card"><div class="eyebrow">You made it to the end WUUUUUUUUUU!!!!</div><h2>You did it ❤️</h2><p>If you got here and you appreciate this little gift...<br>tell me this code:</p><div class="code">I'm amazing and I am the best girl and girlfriend of the existence!</div><p>I love you infinitely, Celina, my love.<br>Thank you for being the best girlfriend in the world.</p><div class="letter">“Thank you for promissing me all of that! You have now won infinite kisses and your boyfriend for your entire life :) (You already had it before but whatever jajaja) ❤️”</div><button class="gift">Open your virtual gift :) 🎁</button><div class="gift-open" hidden>🚙 <strong>A White Jimny</strong> - one day, it is yours. I know this emoji is not white, sowwy jajajaja</div></section>`;for(let i=0;i<100;i++)setTimeout(confetti,i*22);app.querySelector('.gift').onclick=e=>{e.currentTarget.hidden=true;app.querySelector('.gift-open').hidden=false;burst()}}
function confetti(){let e=document.createElement('i');e.className='confetti';e.style.left=Math.random()*100+'vw';e.style.top='-20px';e.style.background=['#ff3f78','#fff','#ffd15f','#8ee8ff'][Math.floor(Math.random()*4)];e.style.transform=`rotate(${Math.random()*360}deg)`;document.body.append(e);setTimeout(()=>e.remove(),3300)}
document.querySelector('#start').onclick=renderQuiz;document.querySelector('#sound').onclick=()=>{audioOn=!audioOn;document.querySelector('#sound').style.opacity=audioOn?'1':'.55';tone()};document.querySelector('#secret-heart').onclick=()=>{heartClicks++;burst();if(heartClicks===10)showToast('Little Caio Secret Unlocked: You are my favorite person and the love of my life. Always and forever. ❤️')};
function roses(){for(let i=0;i<26;i++){let e=document.createElement('span');e.className='rose';e.textContent='🌹';e.style.left=Math.random()*100+'vw';e.style.top=(-20-Math.random()*300)+'px';e.style.animationDelay=(Math.random()*.5)+'s';document.body.append(e);setTimeout(()=>e.remove(),3600)}}
document.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;holdTimer=setTimeout(roses,3000)});document.addEventListener('pointerup',()=>clearTimeout(holdTimer));document.addEventListener('pointercancel',()=>clearTimeout(holdTimer));